const Constants = {
    DATA_RETRIEVE_SUCCESS : "Data collated successfully",
    SIGNUP_SUCCESS : "Signup successful",
    DATA_EMPTY : "Empty data",
    LOGIN_SUCCESS : "Login was successful",
    LOGIN_FAILED : "Login failed",
    USER_EXISTS : "an account with this username exists",
    USER_NOT_EXIST : "Account with this username does not exist",
    REGISTER_FAIL : "Registration failed",
    REGISTER_SUCCESS : "Registration successful",
    DELETE_SUCCESS : "Delete success",
    DELETE_FAILED : "Delete failed",
    EMAIL_EXISTS : "Account already exists",
    DB_ERROR : "Something wrong from our end",
    API_KEY_NOT_EXIST : "Apikey/Api secret not set",
    API_KEY_INVALID : "Apikey is invalid",
    KEY_EMPTY : "Key fields are empty",
    API_KEY_SUCCESS : "Binance keys submitted successfully",
    API_KEY_FAIL : "Binance keys failed to submit",
    LEVERAGE_SETUP_FAIL : "Leverage update failed",
    LEVERAGE_SETUP_SUCCESS : "Leverage update successful",
    ERROR_FETCHING_DATA : "There was an error fetching sufficient data from our end. Sorry",
    MARGIN_INSUFFICIENT : "Available balance is not enough to run the bot; Please do increase your wallet balance or leverage. Min_notional not met",
    BOT_START_FAIL : "Error starting bot",
    BOT_START_SUCCESS : "Bot started successfully",
    BOT_STOP_FAIL : "Error stopping bot",
    BOT_STOP_SUCCESS : " Bot stopped successfully",
    USER_NOT_FOUND : "User not found",
    AFRIC_DETAILS_SAVED_SUCCESS : "Afrigold details saved successfully",
    AFRIC_DETAILS_SAVED_FAIL : "Sorry your afrigold details could not be saved",
    AFRIC_DETAILS_NOT_FOUND : "Your afrigold details have not been set"
}

exports.Constants = Constants;